grpc.server.port=59091

collector.kafka.producer.properties.bootstrap-servers=localhost:9092
collector.kafka.producer.properties.acks=all
collector.kafka.producer.properties.retries=3
kafka.topic.sensors=telemetry.sensors.v1
kafka.topic.hubs=telemetry.hubs.v1
