spring:
  application:
    name: payment
  cloud:
    openfeign:
      enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
  sql:
    init:
      mode: always

server:
  port: 0
