grpc.server.port=59092

aggregator.kafka.producer.properties.bootstrap-servers=localhost:9092
aggregator.kafka.producer.properties.acks=all
aggregator.kafka.producer.properties.retries=3
aggregator.kafka.producer.kafka.topic.snapshots=telemetry.snapshots.v1
aggregator.kafka.consumer.properties.bootstrap-servers=localhost:9092
aggregator.kafka.consumer.properties.groupId=consumer-service-1
aggregator.kafka.consumer.properties.incomingTopic=telemetry.sensors.v1
