grpc.client.hub-router.address=static://localhost:59090
grpc.client.hub-router.enableKeepAlive=true
grpc.client.hub-router.keepAliveWithoutCalls=true
grpc.client.hub-router.negotiationType=plaintext
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
analyzer.kafka.producer.properties.bootstrapServers=localhost:9092
analyzer.kafka.producer.properties.acks=all
analyzer.kafka.producer.properties.retries=3
analyzer.kafka.consumer.properties.hubEventsTopic=telemetry.hubs.v1
analyzer.kafka.consumer.properties.snapshotEventsTopic=telemetry.snapshots.v1