grpc:
  client:
    hub-router:
      address: 'discovery:///hub-router'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

analyzer:
  kafka:
    producer:
      properties:
        bootstrapServers: localhost:9092
        acks: all
        retries: 3
    consumer:
      properties:
        hubEventsTopic: telemetry.hubs.v1
        snapshotEventsTopic: telemetry.snapshots.v1
enable:
  auto:
    commit: false